name: Say hello

on:
  workflow_dispatch:

permissions: read-all

jobs:
  sayhello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout my repo
        uses: actions/checkout@v3

      - name: Say hello
        run: |
          echo "Hello World"
        shell: bash
